### ISSUE TITLE
CÒN ĐIỀU GÌ CHƯA ỔN TRONG ĐỒ ÁN NÀY KHÔNG CÁC BẠN

### ISSUE THREAD

**Issue by PhungThanhTu** [PhungThanhTu/StudentEnrollment#1]

**Comment by eNViDAT0001** [comment]
-Hiện messagebox khi click OK trong set benchmark
-Khóa quyền set benchmark đối với user
-KCB, CB là gì vậy @@?
-Sau khi click confirm score thì khóa chức năng set benchmark lại
-Thêm messagebox để confirm "CONFIRM SCORE" button

**Comment by PhungThanhTu** [comment]
7/4/2021 4:50 AM  : thay đổi title windows :
+ crucial mark setter thành benchmark setter
+ score entering đổi thành "enter score for : so_phach
7/4/2021 4:54 AM : yêu cầu quyền admin để sửa điểm chuẩn

**Comment by PhungThanhTu** [comment]
7/4/2021 4:57 AM :  thêm thông báo sửa thành công điểm chuẩn

**Comment by eNViDAT0001** [comment]
-Hiện messagebox khi click OK trong set benchmark
-Khóa quyền set benchmark đối với user
-Sau khi click confirm score thì không khóa chức năng set benchmark lại
-Thêm messagebox để confirm "CONFIRM SCORE" button
